<h1 align="center"> Perceptron with Numpy arrays </h1>
<h2 align="center"> Perceptron Learning with Numpy with bipolar step function as activation function </h2>


### Why Numpy
The use of python Numpy library module makes the Neural Network computations concise, intuitive and efficient. The increased efficiency results from Numpy's highly optimized scientific computing capabilities. This notebook uses Numpy library for the binary perceptron computations.
## 1. Input patterns and parameters.
It is assumed that the $m$ patterns are available as a python list of sublists with each sublist having values for $ni$ inputs and an expected or desired output. The outputs are expressed in binary. We start by coverting the patterns in to a Numpy two dimensional array and extract various Super Parameters of the network from it.

### The super parameters: 
Normally the super parameters determine the nature of parameters of the neural network. But in the case of this notebook, we will assume that the training patterns are available as list of lists and proceed to determine some of the super parameters from it.

In [36]:
import numpy as np
# each pattern has values for inputs and corresponding desired output
patterns = np.array([(0,0,-1),(0,1,1),(1,0,-1),(1,1,-1)]) 
m = patterns.shape[0] # number of patterns
ni = patterns.shape[1] -1 # ni is number of inputs assuming one output node
X=patterns[:,:ni].T # input matrix with each column representing an input vector
desiredOutputs =patterns[:,ni] # one desired output for each input vector
augmentedInputs=np.insert(X,0,-1,axis=0)
print(augmentedInputs)
#currentWeights = np.zeros(ni)  # weight vector initialized to zeros

[[-1 -1 -1 -1]
 [ 0  0  1  1]
 [ 0  1  0  1]]


In [37]:
def feedForward (weights):
    """ Generates bipolar outputs by thresholding the weighted inputs """
    nets = np.dot(weights.T,augmentedInputs)
    outputs = np.where(nets<0,-1,1)
    return outputs 
print(feedForward(np.array([-.1,.3,-.9])))

[ 1 -1  1 -1]


In [38]:
def tabulate (weights) :
    """ Display the table of inputs and desired and computed outputs """
    print(" training with ",weights)
    computedOutputs = feedForward(weights)
    for i in range(m) :
        desired = desiredOutputs[i]
        computed = computedOutputs[i]
        print("pattern "+str(i+1),patterns[i][0],patterns[i][1],desired,computed)
tabulate(np.array([-.1,.3,-.9]))

 training with  [-0.1  0.3 -0.9]
pattern 1 0 0 -1 1
pattern 2 0 1 1 -1
pattern 3 1 0 -1 1
pattern 4 1 1 -1 -1


In [39]:
def train(weights,pn) :
    """ Implement Perceptron learning algorithm for pattern pn"""
    currentInputs = augmentedInputs[:,pn]
    computedOutputs = feedForward(weights)
    tabulate(weights)
    print(pn,weights,currentInputs, computedOutputs)
    computedOutput = computedOutputs[pn]
    desiredOutput = desiredOutputs[pn]
    newWeights = np.copy(weights)
    print(desiredOutput,computedOutput)
    if computedOutput != desiredOutput:
        if computedOutput == -1 :
            newWeights = weights + currentInputs
        if computedOutput == 1 :
            newWeights = weights - currentInputs
        print(weights," changed to ",newWeights)
    else :
        print(" No changes in weights")
    return np.copy(newWeights)
wts = np.array([-.1,.3, -.9])
for i in range(20) :
    nw = train(wts,i%4)
    tabulate(nw)
    wts=np.copy(nw)

print(nw)

 training with  [-0.1  0.3 -0.9]
pattern 1 0 0 -1 1
pattern 2 0 1 1 -1
pattern 3 1 0 -1 1
pattern 4 1 1 -1 -1
0 [-0.1  0.3 -0.9] [-1  0  0] [ 1 -1  1 -1]
-1 1
[-0.1  0.3 -0.9]  changed to  [ 0.9  0.3 -0.9]
 training with  [ 0.9  0.3 -0.9]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 -1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 -1
 training with  [ 0.9  0.3 -0.9]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 -1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 -1
1 [ 0.9  0.3 -0.9] [-1  0  1] [-1 -1 -1 -1]
1 -1
[ 0.9  0.3 -0.9]  changed to  [-0.1  0.3  0.1]
 training with  [-0.1  0.3  0.1]
pattern 1 0 0 -1 1
pattern 2 0 1 1 1
pattern 3 1 0 -1 1
pattern 4 1 1 -1 1
 training with  [-0.1  0.3  0.1]
pattern 1 0 0 -1 1
pattern 2 0 1 1 1
pattern 3 1 0 -1 1
pattern 4 1 1 -1 1
2 [-0.1  0.3  0.1] [-1  1  0] [1 1 1 1]
-1 1
[-0.1  0.3  0.1]  changed to  [ 0.9 -0.7  0.1]
 training with  [ 0.9 -0.7  0.1]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 -1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 -1
 training with  [ 0.9 -0.7  0.1]
pattern 1 0 0 -1 -1
p

In [40]:
def trainNet (wts) :
    print("Initial weights ",wts)
    tabulate(wts)
    computedOutputs = feedForward(wts)
    changes=0
    n = 0
    while not np.array_equal(computedOutputs, desiredOutputs) :
        print(n+1," training with pattern ",n%4+1)
        newWts = train(wts,n%4) 
        if not np.array_equal(newWts, wts) :
            changes += 1
            print(wts," modified to ",newWts)
            tabulate(newWts)
        else :
            print (n+1," iteration no weight change")
        wts = np.copy(newWts)
        n += 1
        computedOutputs = feedForward(wts)
        if n > 1000 :
            print (" Weights did not converge in 1000 iterations")
            break
    print(changes," weight updations in ",n , " iterations")
    return wts,computedOutputs

initialWeights=np.array([1.5,-10,20])
#initialWeights=randomWeights()
fwts,fouts=trainNet(initialWeights)
print("final Weights = ",fwts," final outputs ",fouts)

Initial weights  [  1.5 -10.   20. ]
 training with  [  1.5 -10.   20. ]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 1
1  training with pattern  1
 training with  [  1.5 -10.   20. ]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 1
0 [  1.5 -10.   20. ] [-1  0  0] [-1  1 -1  1]
-1 -1
 No changes in weights
1  iteration no weight change
2  training with pattern  2
 training with  [  1.5 -10.   20. ]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 1
1 [  1.5 -10.   20. ] [-1  0  1] [-1  1 -1  1]
1 1
 No changes in weights
2  iteration no weight change
3  training with pattern  3
 training with  [  1.5 -10.   20. ]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 1
pattern 3 1 0 -1 -1
pattern 4 1 1 -1 1
2 [  1.5 -10.   20. ] [-1  1  0] [-1  1 -1  1]
-1 -1
 No changes in weights
3  iteration no weight change
4  training with pattern  4
 training with  [  1.5 -10.   20. ]
pattern 1 0 0 -1 -1
pattern 2 0 1 1 1
pattern 3